/* YEP DEMO — a small 1-bit walkaround RPG.
   No build step: plain canvas + the PNG atlases in ./assets
   (generated by tools/yepdemo/make_assets.py). */
(() => {
  'use strict';

  const W = 240, H = 160, T = 16;
  const canvas = document.getElementById('game');
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;

  // ------------------------------------------------------------ maps
  // Outdoors: '.' ',' grass  ':' path  '~' water  'T' tree  'b' bush  'r' rock
  // 'f' flowers  '=' fence  'S' sign  'W' well  'L' lamp  'G' grave
  // 'R' roof  'E' roof edge  'B' brick  'O' window  'D' door
  // Indoors: 'H' wall  '_' floor  'K' shelf  'A' table  'Z' bed  'P' pot
  // 'U' rug  'M' door mat (exit)
  const MAPS = {
    town: {
      base: 'grass',
      rows: [
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        'TTT,........TT....TT..,.,....TTT',
        'TT.RRRRR.b....,.,,,.b,RRRRR...TT',
        'T..EEEEE..T...f....T..EEEEE.,,,T',
        'T,,BODOB.,...,...f,,..BODOB,r,.T',
        'T...,:...,...S..,..,,...:.....,T',
        'T,::::::::::::::::::::::::::::.T',
        'T.,,.......,L.,:..L..........,.T',
        'T.,....f..,.,..:.........f.....T',
        'T..,,.,,b...,..:..,..b..,...,..T',
        'TT,...,...,.,:::::..,...,,.T,.TT',
        'TT,r.....,.f,::W::.f.,.,.,..,..T',
        'T...f........:::::.,,S...,.r,..T',
        'T.,...,...,.,.,:,,.,...~~~~~~..T',
        'T.========..b..:,,b.,.~~~~~~~~.T',
        'T,=......=.....:.,,...~~~~~~~~.T',
        'T,=.G.G.G=S.,.,:,..,..~~~~~~~~.T',
        'T.=......:::::::...,,.~~~~~~~~.T',
        'T.=......=.,.,.:..r...~~~~~~~~.T',
        'T,=.G.G..=.....:,..,...~~~~~~..T',
        'T.=......=T,,,.:.f..T.,.,...,..T',
        'T,========.TT.,,...TT.....b,...T',
        'T..,...,,....,,...,.,.,,,......T',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      ],
      warps: { '5,4': ['library', 4, 6, 'up'], '24,4': ['cottage', 3, 5, 'up'] },
    },
    library: {
      base: 'floor',
      rows: [
        'HHHHHHHHHH',
        'KKK____KKK',
        '__________',
        '__UUU_____',
        '__UUU__A__',
        '__________',
        'P________P',
        '    M     ',
      ],
      warps: { '4,7': ['town', 5, 5, 'down'] },
    },
    cottage: {
      base: 'floor',
      rows: [
        'HHHHHHHH',
        'Z__K___P',
        '________',
        '__A_____',
        '_____UU_',
        '________',
        '   M    ',
      ],
      warps: { '3,6': ['town', 24, 5, 'down'] },
    },
  };

  // char -> [tile, solid, drawnOverBase]
  const TILEDEF = {
    '.': ['grass', 0], ',': ['grass2', 0], ':': ['path', 0], '~': ['water', 1],
    'T': ['tree', 1, 1], 'b': ['bush', 1, 1], 'r': ['rock', 1, 1], 'f': ['flower', 0, 1],
    '=': ['fence', 1, 1], 'S': ['sign', 1, 1], 'W': ['well', 1, 1], 'L': ['lamp', 1, 1],
    'G': ['grave', 1, 1], 'R': ['roof', 1], 'E': ['roof_edge', 1], 'B': ['brick', 1],
    'O': ['window', 1], 'D': ['door', 0],
    'H': ['wallpaper', 1], '_': ['floor', 0], 'K': ['shelf', 1, 1], 'A': ['table', 1, 1],
    'Z': ['bed', 1, 1], 'P': ['pot', 1, 1], 'U': ['rug', 0], 'M': ['mat', 0],
    ' ': [null, 1],
  };

  // ------------------------------------------------------------ words
  const ITEMS = {
    d20: 'the D20',
    page: 'the script page',
    key: 'the theatre key',
  };

  const SIGNS = {
    'town:13,5': ['YEP TOWN', 'Population: small. Weather: foggy, with a chance of plot.'],
    'town:21,12': ['NO SWIMMING.', 'The fish are in rehearsal.'],
    'town:10,16': ['RETIRED PROPS', 'Please do not wake them.'],
  };

  const GRAVES = [
    'HERE LIES THE FOURTH WALL.',
    'HERE LIES A PERFECTLY GOOD IDEA. CUT FOR TIME.',
    'R.I.P. THE SECOND ACT.',
    'IN LOVING MEMORY OF THE UNDERSTUDY. SHE WAS READY.',
    'This one just says "YEP."',
  ];

  const LOOK = {
    'W': ['You look down the well. Your reflection waves first.'],
    'K': ['Plays, games, and things in between.'],
    'Z': ['Not tired yet.'],
    'P': ['An empty pot. Very dramatic.'],
    'A': ['Half a sandwich and a highlighted script.'],
    'L': ['The lamp hums a note. Slightly flat.'],
    '~': ['The water is cold and full of opinions.'],
  };

  // ------------------------------------------------------------ state
  const S = {
    scene: 'title',     // title | play
    map: 'town',
    items: [],
    opened: {},
    elderMet: false,
    done: false,
    frame: 0,
    fade: 0,            // 0..4 dither level
    fadeTo: null,
    dialog: null,
    muted: false,
  };

  function actor(map, x, y, dir, kind, opts = {}) {
    return Object.assign({
      map, x, y, px: x * T, py: y * T, dir, kind,
      moving: false, tx: x, ty: y, stepCount: 0, speed: 1,
      home: [x, y], wander: 0, timer: 60 + Math.random() * 120,
    }, opts);
  }

  const player = actor('town', 15, 8, 'down', 'player', { speed: 2 });

  const npcs = [
    actor('town', 14, 11, 'down', 'elder', { talk: talkElder }),
    actor('town', 27, 8, 'left', 'cat', { wander: 2, talk: () => [pick(['Mrrp.', 'The cat looks at you like you forgot your line.', 'The cat is busy being a cat.'])] }),
    actor('town', 5, 17, 'down', 'ghost', {
      wander: 2, talk: () => S.items.includes('key')
        ? ['You found it! Places, everyone. PLACES.']
        : ['Boo. Sorry. Force of habit.', 'I was a stage manager. Now I haunt this yard and still call places.', 'Someone dropped a key in that chest. I\'d grab it, but. You know. Hands.'],
    }),
    actor('library', 6, 3, 'down', 'kid', {
      wander: 1, talk: () => S.items.includes('page')
        ? ['You found the missing page! It says "EXIT, PURSUED BY A BEAR." Classic.']
        : ['I\'ve read every book in here. Twice.', 'My favorite one is missing a page. Try the cottage across the square.'],
    }),
  ];

  const chests = [
    { map: 'town', x: 29, y: 21, item: 'd20' },
    { map: 'town', x: 3, y: 20, item: 'key' },
    { map: 'cottage', x: 5, y: 1, item: 'page' },
  ];

  function talkElder() {
    const n = S.items.length;
    if (S.done) return [pick(['Surprise yourself!', 'Go on, walk around. That\'s the whole game for now.'])];
    if (n === 3) {
      S.done = true;
      return ['The D20! The page! The key!', 'Now the theatre can open and the real game can start.', '...which is to say, that\'s the end of the demo. Thanks for walking around.'];
    }
    if (!S.elderMet) {
      S.elderMet = true;
      return ['Oh! Hello. You\'re new.', 'The fog came through last night and the town lost three things: a D20, a page of a script, and the theatre key.', 'Find them and bring them here. I\'ll be at the well. I\'m always at the well.'];
    }
    return [`${n} of 3 so far. Keep walking around. That's most of the job.`];
  }

  const pick = (a) => a[(Math.random() * a.length) | 0];

  // ------------------------------------------------------------ assets
  const img = {};
  let atlas;
  async function load() {
    atlas = await (await fetch('assets/atlas.json')).json();
    await Promise.all(['tiles', 'sprites', 'font'].map((n) => new Promise((ok, fail) => {
      const i = new Image();
      i.onload = () => { img[n] = i; ok(); };
      i.onerror = fail;
      i.src = `assets/${n}.png`;
    })));
    // white copy of the font for text on black
    const c = document.createElement('canvas');
    c.width = img.font.width; c.height = img.font.height;
    const g = c.getContext('2d');
    g.drawImage(img.font, 0, 0);
    g.globalCompositeOperation = 'source-in';
    g.fillStyle = '#fff';
    g.fillRect(0, 0, c.width, c.height);
    img.fontWhite = c;
    // Bayer-dither fade patterns, levels 1..3 (0 = clear, 4 = solid black)
    const bayer = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5];
    img.dither = [null];
    for (let lv = 1; lv <= 3; lv++) {
      const p = document.createElement('canvas');
      p.width = p.height = 4;
      const pg = p.getContext('2d');
      pg.fillStyle = '#000';
      bayer.forEach((v, i) => { if (v < lv * 4) pg.fillRect(i % 4, (i / 4) | 0, 1, 1); });
      img.dither.push(ctx.createPattern(p, 'repeat'));
    }
  }

  function drawCell(sheet, name, x, y, flipX) {
    const i = (sheet === 'tiles' ? atlas.tiles : atlas.sprites)[name];
    if (i === undefined) return;
    const sx = (i % atlas.cols) * T, sy = ((i / atlas.cols) | 0) * T;
    ctx.drawImage(img[sheet], sx, sy, T, T, x | 0, y | 0, T, T);
  }

  function text(str, x, y, white) {
    const f = white ? img.fontWhite : img.font;
    for (let i = 0; i < str.length; i++) {
      const c = str.charCodeAt(i) - 32;
      if (c <= 0 || c > 94) continue;
      ctx.drawImage(f, (c % 16) * 8, ((c / 16) | 0) * 8, 8, 8, x + i * 8, y, 8, 8);
    }
  }

  function bigText(str, x, y, scale) {
    for (let i = 0; i < str.length; i++) {
      const c = str.charCodeAt(i) - 32;
      if (c <= 0 || c > 94) continue;
      ctx.drawImage(img.fontWhite, (c % 16) * 8, ((c / 16) | 0) * 8, 8, 8, x + i * 8 * scale, y, 8 * scale, 8 * scale);
    }
  }

  // ------------------------------------------------------------ sound
  let audio;
  function beep(freq, dur = 0.04, vol = 0.04) {
    if (S.muted) return;
    try {
      audio = audio || new (window.AudioContext || window.webkitAudioContext)();
      if (audio.state === 'suspended') audio.resume();
      const o = audio.createOscillator(), g = audio.createGain();
      o.type = 'square';
      o.frequency.value = freq;
      g.gain.value = vol;
      g.gain.exponentialRampToValueAtTime(0.0001, audio.currentTime + dur);
      o.connect(g).connect(audio.destination);
      o.start();
      o.stop(audio.currentTime + dur);
    } catch (e) { /* no audio, no problem */ }
  }
  const jingle = () => [523, 659, 784, 1046].forEach((f, i) => setTimeout(() => beep(f, 0.12, 0.05), i * 110));

  // ------------------------------------------------------------ input
  const held = { up: 0, down: 0, left: 0, right: 0, a: 0, b: 0 };
  let pressedA = false;
  const KEYS = {
    ArrowUp: 'up', KeyW: 'up', ArrowDown: 'down', KeyS: 'down',
    ArrowLeft: 'left', KeyA: 'left', ArrowRight: 'right', KeyD: 'right',
    KeyZ: 'a', Enter: 'a', Space: 'a', KeyX: 'b', ShiftLeft: 'b', ShiftRight: 'b',
  };
  addEventListener('keydown', (e) => {
    if (e.code === 'KeyM') { toggleMute(); return; }
    const k = KEYS[e.code];
    if (!k) return;
    e.preventDefault();
    if (k === 'a' && !held.a) pressedA = true;
    held[k] = 1;
  });
  addEventListener('keyup', (e) => { const k = KEYS[e.code]; if (k) held[k] = 0; });
  addEventListener('blur', () => Object.keys(held).forEach((k) => (held[k] = 0)));

  function toggleMute() {
    S.muted = !S.muted;
    const b = document.getElementById('mute');
    if (b) b.textContent = S.muted ? 'SOUND OFF' : 'SOUND ON';
  }
  document.getElementById('mute')?.addEventListener('click', toggleMute);

  // touch: d-pad reads direction from where the finger is, so sliding works
  const pad = document.getElementById('dpad');
  if (pad) {
    const setDir = (e) => {
      const r = pad.getBoundingClientRect();
      const dx = e.clientX - (r.left + r.width / 2), dy = e.clientY - (r.top + r.height / 2);
      held.up = held.down = held.left = held.right = 0;
      if (Math.hypot(dx, dy) < r.width * 0.12) return;
      if (Math.abs(dx) > Math.abs(dy)) held[dx > 0 ? 'right' : 'left'] = 1;
      else held[dy > 0 ? 'down' : 'up'] = 1;
    };
    const clear = () => { held.up = held.down = held.left = held.right = 0; };
    pad.addEventListener('pointerdown', (e) => { pad.setPointerCapture(e.pointerId); setDir(e); e.preventDefault(); });
    pad.addEventListener('pointermove', (e) => { if (e.buttons || e.pointerType === 'touch') setDir(e); });
    pad.addEventListener('pointerup', clear);
    pad.addEventListener('pointercancel', clear);
  }
  for (const [id, k] of [['btn-a', 'a'], ['btn-b', 'b']]) {
    const el = document.getElementById(id);
    if (!el) continue;
    el.addEventListener('pointerdown', (e) => { e.preventDefault(); if (k === 'a') pressedA = true; held[k] = 1; });
    el.addEventListener('pointerup', () => (held[k] = 0));
    el.addEventListener('pointercancel', () => (held[k] = 0));
    el.addEventListener('pointerleave', () => (held[k] = 0));
  }

  // ------------------------------------------------------------ world
  const DIRS = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };
  const map = () => MAPS[S.map];
  const charAt = (m, x, y) => (MAPS[m].rows[y] || '')[x] ?? ' ';

  function occupied(m, x, y, self) {
    if (TILEDEF[charAt(m, x, y)][1]) return true;
    if (chests.some((c) => c.map === m && c.x === x && c.y === y)) return true;
    for (const a of [player, ...npcs]) {
      if (a === self || a.map !== m) continue;
      if ((a.x === x && a.y === y) || (a.moving && a.tx === x && a.ty === y)) return true;
    }
    return false;
  }

  function tryMove(a, dir) {
    a.dir = dir;
    const [dx, dy] = DIRS[dir];
    const nx = a.x + dx, ny = a.y + dy;
    if (occupied(a.map, nx, ny, a)) return false;
    a.moving = true; a.tx = nx; a.ty = ny;
    return true;
  }

  function stepActor(a, speed) {
    if (!a.moving) return false;
    const gx = a.tx * T, gy = a.ty * T;
    a.px += Math.sign(gx - a.px) * Math.min(speed, Math.abs(gx - a.px));
    a.py += Math.sign(gy - a.py) * Math.min(speed, Math.abs(gy - a.py));
    if (a.px === gx && a.py === gy) {
      a.x = a.tx; a.y = a.ty; a.moving = false; a.stepCount++;
      return true;
    }
    return false;
  }

  let turnHold = 0, lastDirHeld = null, bumpTimer = 0;
  function heldDir() {
    // most recently meaningful: prefer keeping the current direction if still held
    if (lastDirHeld && held[lastDirHeld]) return lastDirHeld;
    lastDirHeld = ['up', 'down', 'left', 'right'].find((d) => held[d]) || null;
    return lastDirHeld;
  }

  function updatePlayer() {
    const speed = held.b ? 4 : 2;
    if (player.moving) {
      if (stepActor(player, speed)) arrive();
      if (player.moving) return;
    }
    const d = heldDir();
    if (!d) { turnHold = 0; return; }
    // a quick tap turns in place; holding walks
    if (d !== player.dir && turnHold === 0) { player.dir = d; turnHold = 1; return; }
    if (turnHold > 0 && turnHold < 5) { turnHold++; if (!held[d]) turnHold = 0; return; }
    if (!tryMove(player, d)) {
      if (bumpTimer <= 0) { beep(90, 0.05, 0.03); bumpTimer = 18; }
    }
  }

  function arrive() {
    const w = map().warps[`${player.x},${player.y}`];
    if (w) {
      beep(330, 0.06); setTimeout(() => beep(247, 0.08), 70);
      S.fadeTo = w;
    }
  }

  function doWarp([m, x, y, dir]) {
    S.map = m;
    Object.assign(player, { map: m, x, y, tx: x, ty: y, px: x * T, py: y * T, dir, moving: false });
  }

  function updateNPC(n) {
    if (n.map !== S.map) return;
    if (n.moving) { stepActor(n, 1); return; }
    if (!n.wander || S.dialog) return;
    if (--n.timer > 0) return;
    n.timer = 90 + Math.random() * 180;
    const d = pick(Object.keys(DIRS));
    const [dx, dy] = DIRS[d];
    if (Math.abs(n.x + dx - n.home[0]) > n.wander || Math.abs(n.y + dy - n.home[1]) > n.wander) { n.dir = d; return; }
    tryMove(n, d);
  }

  function interact() {
    const [dx, dy] = DIRS[player.dir];
    const x = player.x + dx, y = player.y + dy;
    const npc = npcs.find((n) => n.map === S.map && n.x === x && n.y === y && !n.moving);
    if (npc) {
      npc.dir = { up: 'down', down: 'up', left: 'right', right: 'left' }[player.dir];
      return say(npc.talk());
    }
    const chest = chests.find((c) => c.map === S.map && c.x === x && c.y === y);
    if (chest) {
      const id = `${chest.map}:${chest.x},${chest.y}`;
      if (S.opened[id]) return say(['It\'s empty.']);
      S.opened[id] = true;
      S.items.push(chest.item);
      jingle();
      const n = S.items.length;
      return say([`You found ${ITEMS[chest.item]}! (${n}/3)`, n === 3 ? 'That\'s everything. Back to the well!' : null].filter(Boolean));
    }
    const c = charAt(S.map, x, y);
    const key = `${S.map}:${x},${y}`;
    if (c === 'S' && SIGNS[key]) return say(SIGNS[key]);
    if (c === 'G') return say([GRAVES[(x * 7 + y * 3) % GRAVES.length]]);
    if (LOOK[c]) return say(LOOK[c]);
  }

  // ------------------------------------------------------------ dialog
  const COLS = 27, LINES = 3;
  function wrap(s) {
    const out = [];
    let line = '';
    for (const w of s.split(' ')) {
      if ((line + (line ? ' ' : '') + w).length > COLS) { out.push(line); line = w; }
      else line += (line ? ' ' : '') + w;
    }
    if (line) out.push(line);
    return out;
  }
  function say(pages) {
    const out = [];
    for (const p of pages) {
      const lines = wrap(p);
      for (let i = 0; i < lines.length; i += LINES) out.push(lines.slice(i, i + LINES));
    }
    S.dialog = { pages: out, page: 0, shown: 0 };
  }
  function updateDialog() {
    const d = S.dialog;
    const total = d.pages[d.page].join('').length;
    if (d.shown < total) {
      d.shown += held.a || held.b ? 3 : 1;
      if (d.shown % 3 === 0) beep(880 + (d.shown % 7) * 20, 0.02, 0.02);
      if (pressedA) d.shown = total;
    } else if (pressedA) {
      beep(660, 0.03);
      if (++d.page >= d.pages.length) S.dialog = null;
      else d.shown = 0;
    }
  }
  function drawDialog() {
    const d = S.dialog;
    const y = H - 48;
    ctx.fillStyle = '#000'; ctx.fillRect(2, y, W - 4, 46);
    ctx.fillStyle = '#fff'; ctx.fillRect(4, y + 2, W - 8, 42);
    ctx.fillStyle = '#000'; ctx.fillRect(6, y + 4, W - 12, 38);
    ctx.fillStyle = '#fff'; ctx.fillRect(7, y + 5, W - 14, 36);
    let left = d.shown;
    d.pages[d.page].forEach((line, i) => {
      text(line.slice(0, Math.max(0, left)), 12, y + 9 + i * 11);
      left -= line.length;
    });
    const total = d.pages[d.page].join('').length;
    if (d.shown >= total && (S.frame >> 4) % 2) drawCell('sprites', 'arrow', W - 24, y + 30);
  }

  // ------------------------------------------------------------ draw
  function drawWorld() {
    const m = map();
    const mw = m.rows[0].length * T, mh = m.rows.length * T;
    const cx = mw <= W ? (mw - W) / 2 : Math.max(0, Math.min(mw - W, player.px + 8 - W / 2));
    const cy = mh <= H ? (mh - H) / 2 : Math.max(0, Math.min(mh - H, player.py + 8 - H / 2));
    const ox = -Math.round(cx), oy = -Math.round(cy);
    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, W, H);

    const x0 = Math.max(0, Math.floor(cx / T)), y0 = Math.max(0, Math.floor(cy / T));
    const water = (S.frame >> 5) % 2 ? 'water1' : 'water0';
    for (let y = y0; y < Math.min(m.rows.length, y0 + H / T + 2); y++) {
      for (let x = x0; x < Math.min(m.rows[y].length, x0 + W / T + 2); x++) {
        const def = TILEDEF[m.rows[y][x]];
        if (!def || !def[0]) continue;
        const px = ox + x * T, py = oy + y * T;
        if (def[2]) drawCell('tiles', m.base, px, py);
        drawCell('tiles', def[0] === 'water' ? water : def[0], px, py);
      }
    }
    for (const c of chests) {
      if (c.map !== S.map) continue;
      drawCell('tiles', S.opened[`${c.map}:${c.x},${c.y}`] ? 'chest_open' : 'chest', ox + c.x * T, oy + c.y * T);
    }
    const actors = [player, ...npcs.filter((n) => n.map === S.map)].sort((a, b) => a.py - b.py);
    for (const a of actors) drawActor(a, ox, oy);

    // speech bubble over the elder until you've met
    if (S.map === 'town' && !S.elderMet) {
      const e = npcs[0];
      drawCell('sprites', 'bubble', ox + e.px, oy + e.py - 13 + ((S.frame >> 5) % 2));
    }
  }

  function drawActor(a, ox, oy) {
    let name;
    if (a.kind === 'player') {
      const walking = a.moving;
      const phase = walking && (Math.abs(a.px - a.tx * T) + Math.abs(a.py - a.ty * T)) < 9;
      if (a.dir === 'left' || a.dir === 'right') name = `p_${a.dir}${walking && phase ? 1 : 0}`;
      else name = `p_${a.dir}${walking && phase ? (a.stepCount % 2 ? 1 : 2) : 0}`;
    } else {
      name = `${a.kind}${(S.frame >> 5) % 2}`;
    }
    const bob = a.kind === 'ghost' ? Math.round(Math.sin(S.frame / 20) * 1.5) - 2 : 0;
    drawCell('sprites', name, ox + a.px, oy + a.py - 2 + bob);
  }

  function drawHUD() {
    if (!S.items.length) return;
    const w = S.items.length * 16 + 4;
    ctx.fillStyle = '#000'; ctx.fillRect(W - w - 4, 2, w + 2, 20);
    ctx.fillStyle = '#fff'; ctx.fillRect(W - w - 3, 3, w, 18);
    S.items.forEach((it, i) => drawCell('sprites', it, W - w - 1 + i * 16, 4));
  }

  function drawTitle() {
    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, W, H);
    bigText('YEP', (W - 3 * 24) / 2, 28, 3);
    text('A 1-BIT WALKAROUND', (W - 18 * 8) / 2, 62, true);
    // a little parade across the title
    const t = S.frame;
    const px = ((t * 0.75) % (W + 64)) - 32;
    ctx.fillStyle = '#fff';
    ctx.fillRect(0, 88, W, 24);
    drawCell('sprites', `p_right${(t >> 3) % 2}`, px, 92);
    drawCell('sprites', `cat${(t >> 4) % 2}`, px - 24, 92);
    drawCell('sprites', `ghost${(t >> 5) % 2}`, px - 52, 90 + Math.round(Math.sin(t / 20)));
    if ((t >> 5) % 2) {
      const msg = matchMedia('(pointer: coarse)').matches ? 'TAP A TO START' : 'PRESS Z TO START';
      text(msg, (W - msg.length * 8) / 2, 126, true);
    }
    text('BUILDING / DEMO', (W - 15 * 8) / 2, 146, true);
  }

  function drawFade() {
    if (S.fade <= 0) return;
    ctx.fillStyle = S.fade >= 4 ? '#000' : img.dither[S.fade];
    ctx.fillRect(0, 0, W, H);
  }

  // ------------------------------------------------------------ loop
  let fadeDir = 0, fadeTick = 0;
  function update() {
    S.frame++;
    if (bumpTimer > 0) bumpTimer--;

    if (fadeDir) {
      if (++fadeTick % 4 === 0) {
        S.fade += fadeDir;
        if (S.fade >= 4) {
          if (S.fadeTo === 'play') S.scene = 'play';
          else if (S.fadeTo) doWarp(S.fadeTo);
          S.fadeTo = null;
          fadeDir = -1;
        } else if (S.fade <= 0) { S.fade = 0; fadeDir = 0; }
      }
      pressedA = false;
      return;
    }
    if (S.fadeTo) { fadeDir = 1; fadeTick = 0; pressedA = false; return; }

    if (S.scene === 'title') {
      if (pressedA) { beep(784, 0.08); S.fadeTo = 'play'; }
    } else if (S.dialog) {
      updateDialog();
    } else {
      if (pressedA && !player.moving) interact();
      else updatePlayer();
    }
    npcs.forEach(updateNPC);
    pressedA = false;
  }

  function render() {
    if (S.scene === 'title') drawTitle();
    else {
      drawWorld();
      drawHUD();
      if (S.dialog) drawDialog();
    }
    drawFade();
  }

  // integer scale when there is room for 2x or more; otherwise fill the space
  function fit() {
    const stage = document.getElementById('stage');
    const r = stage.getBoundingClientRect();
    const s = Math.min((r.width - 16) / W, (r.height - 16) / H); // room for the outline
    const k = s >= 2 ? Math.floor(s) : s;
    canvas.style.width = `${W * k}px`;
    canvas.style.height = `${H * k}px`;
  }
  addEventListener('resize', fit);

  let last = 0, acc = 0;
  function loop(ts) {
    acc += Math.min(100, ts - (last || ts));
    last = ts;
    while (acc >= 1000 / 60) { update(); acc -= 1000 / 60; }
    render();
    requestAnimationFrame(loop);
  }

  load().then(() => { fit(); requestAnimationFrame(loop); }).catch((e) => {
    document.getElementById('stage').textContent = 'Could not load assets.';
    console.error(e);
  });

  // exposed for debugging/tests
  window.YEP = { S, player, npcs, chests, MAPS };
})();
