[build]
  publish = "src"

[[redirects]]
  from = "/helpme"
  to = "https://helpme.leolion.com"
  status = 301
  force = true

[[redirects]]
  from = "/helpme/*"
  to = "https://helpme.leolion.com/:splat"
  status = 301
  force = true
