// Cut parts out of the Poly Haven "Old Gas Mask" (CC0), decimate them with meshoptimizer,
// and bake them into a plain JS module (base64 typed arrays) so the game needs no loader.
// Source: https://polyhaven.com/a/old_gas_mask (1k glTF; the .bin is shared across resolutions).
// Needs: npm i @gltf-transform/core meshoptimizer   (in a scratch dir, not the repo)
//   MASK=1000 FILTER=160 ERR=0.07 node bake-gasmask.mjs <old_gas_mask_1k.gltf> \
//     src/building/intermachinas/assets/characters/gasmask.js [preview.gltf]
// Textures: prep-character-textures.py writes gasmask_d/_n.jpg from the same download.
import { NodeIO, Document } from '@gltf-transform/core';
import { MeshoptSimplifier } from 'meshoptimizer';
import fs from 'fs';

const [, , src, out, viewOut] = process.argv;
await MeshoptSimplifier.ready;
const io = new NodeIO();
const doc = await io.read(src);
const prim = doc.getRoot().listMeshes()[0].listPrimitives()[0];
const P = prim.getAttribute('POSITION').getArray();
const N = prim.getAttribute('NORMAL').getArray();
const U = prim.getAttribute('TEXCOORD_0').getArray();
const I = prim.getIndices().getArray();

function cut(pred, target, err = +(process.env.ERR || 0.06)) {
  const map = new Map(), pos = [], nrm = [], uv = [], idx = [];
  for (let t = 0; t < I.length; t += 3) {
    const c = [0, 0, 0];
    for (let k = 0; k < 3; k++) for (let a = 0; a < 3; a++) c[a] += P[I[t + k] * 3 + a] / 3;
    if (!pred(c)) continue;
    for (let k = 0; k < 3; k++) {
      const v = I[t + k];
      if (!map.has(v)) {
        map.set(v, pos.length / 3);
        pos.push(P[v * 3], P[v * 3 + 1], P[v * 3 + 2]); nrm.push(N[v * 3], N[v * 3 + 1], N[v * 3 + 2]); uv.push(U[v * 2], U[v * 2 + 1]);
      }
      idx.push(map.get(v));
    }
  }
  const p32 = new Float32Array(pos);
  // attribute-aware simplify keeps UV seams / normals sane
  const attrs = new Float32Array(nrm.length / 3 * 5);
  for (let i = 0; i < nrm.length / 3; i++) { attrs.set([nrm[i * 3], nrm[i * 3 + 1], nrm[i * 3 + 2], uv[i * 2], uv[i * 2 + 1]], i * 5); }
  let [si, e] = MeshoptSimplifier.simplifyWithAttributes(new Uint32Array(idx), p32, 3, attrs, 5, [0.5, 0.5, 0.5, 1, 1], null, target * 3, err, []);
  // compact
  const m2 = new Map(), op = [], on = [], ou = [], oi = [];
  for (const v of si) {
    if (!m2.has(v)) { m2.set(v, op.length / 3); op.push(pos[v * 3], pos[v * 3 + 1], pos[v * 3 + 2]); on.push(nrm[v * 3], nrm[v * 3 + 1], nrm[v * 3 + 2]); ou.push(uv[v * 2], uv[v * 2 + 1]); }
    oi.push(m2.get(v));
  }
  console.log('tris', idx.length / 3, '->', oi.length / 3, 'verts', op.length / 3, 'err', e.toFixed(4));
  return { pos: op, nrm: on, uv: ou, idx: oi };
}

const parts = {
  mask: cut((c) => c[1] > -0.2, +process.env.MASK || 900),
  filter: cut((c) => c[1] < -0.79, +process.env.FILTER || 220),
};

const b64 = (arr, T) => Buffer.from(new T(arr).buffer).toString('base64');
let js = `// Generated by tools/intermachinas/bake-gasmask.mjs from Poly Haven "Old Gas Mask" (CC0, Michał Wiśniewski).
// Decimated with meshoptimizer; positions in metres, original model space (mask faces +z).
// Do not edit by hand; re-run the bake script.
const d = (s, T) => { const b = Uint8Array.from(atob(s), (c) => c.charCodeAt(0)); return new T(b.buffer); };
export const GASMASK = {\n`;
for (const [k, p] of Object.entries(parts)) {
  js += `  ${k}: { pos: d('${b64(p.pos, Float32Array)}', Float32Array), nrm: d('${b64(p.nrm, Float32Array)}', Float32Array), uv: d('${b64(p.uv, Float32Array)}', Float32Array), idx: d('${b64(p.idx, Uint16Array)}', Uint16Array) },\n`;
}
js += '};\n';
fs.writeFileSync(out, js);
console.log('wrote', out, (js.length / 1024).toFixed(1), 'KB');

if (viewOut) { // a gltf for eyeballing
  const d2 = new Document(); const buf = d2.createBuffer();
  const tex = d2.createTexture().setImage(fs.readFileSync(src.replace(/[^/]+$/, 'textures/old_gas_mask_diff_1k.jpg'))).setMimeType('image/jpeg');
  const mat = d2.createMaterial().setBaseColorTexture(tex).setRoughnessFactor(0.8).setMetallicFactor(0);
  const scene = d2.createScene();
  for (const [k, p] of Object.entries(parts)) {
    const pr = d2.createPrimitive().setMaterial(mat)
      .setAttribute('POSITION', d2.createAccessor().setType('VEC3').setArray(new Float32Array(p.pos)).setBuffer(buf))
      .setAttribute('NORMAL', d2.createAccessor().setType('VEC3').setArray(new Float32Array(p.nrm)).setBuffer(buf))
      .setAttribute('TEXCOORD_0', d2.createAccessor().setType('VEC2').setArray(new Float32Array(p.uv)).setBuffer(buf))
      .setIndices(d2.createAccessor().setType('SCALAR').setArray(new Uint16Array(p.idx)).setBuffer(buf));
    scene.addChild(d2.createNode(k).setMesh(d2.createMesh(k).addPrimitive(pr)));
  }
  await new NodeIO().write(viewOut, d2);
}
